export const teamMembers = {
  scrumMasters: [
    {
      name: 'Kai Hu',
      avatar: '/Images/avatar.png',
      location: 'Germany',
      email: 'some_email@fake.com',
      phoneNumber: '95729435',
      responsibilities: 'responsibilities',
      specializations: ['Project Management', 'Soft skills', 'Negotiation'],
    },
    {
      name: 'Master MA',
      avatar: '/Images/avatar.png',
      location: 'Lo Bole',
      email: 'ma-MA@ma.com',
      phoneNumber: '39842423432',
      responsibilities: 'responsibilities',
      specializations: ['Architect', 'Leader', 'Sustainability'],
    },
  ],
  productOwners: [
    {
      name: 'UUUUlf',
      avatar: '/Images/avatar.png',
      location: 'Ulfland',
      email: 'uuulfito_dinamito@yeah.com',
      phoneNumber: '94567397',
      responsibilities: 'responsibilities',
      specializations: ['Dragon Slayer', 'Master of Water'],
    },
    {
      name: 'Will Dafoe',
      avatar: '/Images/avatar.png',
      location: 'Hobbiton',
      email: 'dafoe@will.com',
      phoneNumber: '2394572',
      responsibilities: 'responsibilities',
      specializations: ['Big Datanalytics', 'Visionaire'],
    },
  ],
  developers: [
    {
      name: 'El churrascas',
      avatar: '/Images/avatar.png',
      location: 'BcnCity',
      email: 'churras_quito@quitoquito.com',
      phoneNumber: '9423579287',
      responsibilities: 'responsibilities',
      specializations: ['BBQ Master', 'Fastest hand in west'],
    },
    {
      name: 'Noche de Sergelo',
      avatar: '/Images/avatar.png',
      location: 'Paradise City',
      email: 'nocheDeSergel@night.com',
      phoneNumber: '2398457',
      responsibilities: 'responsibilities',
      specializations: ['Sergels Night'],
    },
    {
      name: 'Universal Data Citizen',
      avatar: '/Images/avatar.png',
      location: 'Ill be back',
      email: 'universal.soldier@ssapito.com',
      phoneNumber: 'phone number',
      responsibilities: 'responsibilities',
      specializations: ['Destroyer'],
    },
  ],
  designers: [
    {
      name: 'Sagar the Wizard',
      avatar: '/Images/avatar.png',
      location: 'MiddleSAP',
      email: 'wizard@theWhite.com',
      phoneNumber: '238749',
      responsibilities: 'responsibilities',
      specializations: ['GOD', 'Creates things from nothing'],
    },
  ],
};
